
/* Copyright (c) 1997 Miller Puckette and others. */

/* < https://opensource.org/licenses/BSD-3-Clause > */

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

#include "../../m_spaghettis.h"
#include "../../m_core.h"

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

// ====================================

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

t_symbol s_float    = { "float"     , NULL, NULL };     /* Static. */
t_symbol s_symbol   = { "symbol"    , NULL, NULL };
t_symbol s_bang     = { "bang"      , NULL, NULL };
t_symbol s_list     = { "list"      , NULL, NULL };
t_symbol s_anything = { "anything"  , NULL, NULL };
t_symbol s_signal   = { "signal"    , NULL, NULL };
t_symbol s__N       = { "#N"        , NULL, NULL };
t_symbol s__X       = { "#X"        , NULL, NULL };
t_symbol s__A       = { "#A"        , NULL, NULL };
t_symbol s_         = { ""          , NULL, NULL };

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

/* Static. */

t_symbol *sym_JACK;
t_symbol *sym_Untitled;
t_symbol *sym__VALUE_;
t_symbol *sym__SLOT_;
t_symbol *sym___ampersand__;
t_symbol *sym___ampersand____ampersand__;
t_symbol *sym___arrobe__0;
t_symbol *sym___arrobe__1;
t_symbol *sym___arrobe__2;
t_symbol *sym___arrobe__3;
t_symbol *sym___arrobe__4;
t_symbol *sym___arrobe__5;
t_symbol *sym___arrobe__6;
t_symbol *sym___arrobe__7;
t_symbol *sym___arrobe__8;
t_symbol *sym___arrobe__9;
t_symbol *sym___arrobe__a;
t_symbol *sym___arrobe__b;
t_symbol *sym___arrobe__c;
t_symbol *sym___arrobe__d;
t_symbol *sym___arrobe__e;
t_symbol *sym___arrobe__f;
t_symbol *sym___asterisk__;
t_symbol *sym___asterisk____tilde__;
t_symbol *sym___bar__;
t_symbol *sym___bar____bar__;
t_symbol *sym___comma__;
t_symbol *sym___dash__;
t_symbol *sym___dash____asterisk__;
t_symbol *sym___dash__aif;
t_symbol *sym___dash__aiff;
t_symbol *sym___dash__big;
t_symbol *sym___dash__binary;
t_symbol *sym___dash__bytes;
t_symbol *sym___dash__discard;
t_symbol *sym___dash__elapsed;
t_symbol *sym___dash__format;
t_symbol *sym___dash__frames;
t_symbol *sym___dash__frequency;
t_symbol *sym___dash__global;
t_symbol *sym___dash__growth;
t_symbol *sym___dash__hop;
t_symbol *sym___dash__keep;
t_symbol *sym___dash__little;
t_symbol *sym___dash__next;
t_symbol *sym___dash__nextstep;
t_symbol *sym___dash__none;
t_symbol *sym___dash__normalize;
t_symbol *sym___dash__peaks;
t_symbol *sym___dash__points;
t_symbol *sym___dash__power;
t_symbol *sym___dash__resize;
t_symbol *sym___dash__samplerate;
t_symbol *sym___dash__skip;
t_symbol *sym___dash__stream;
t_symbol *sym___dash__table;
t_symbol *sym___dash__time;
t_symbol *sym___dash__udp;
t_symbol *sym___dash__unit;
t_symbol *sym___dash__vibrato;
t_symbol *sym___dash__wait;
t_symbol *sym___dash__wave;
t_symbol *sym___equals____equals__;
t_symbol *sym___exclamation____equals__;
t_symbol *sym___greater__;
t_symbol *sym___greater____equals__;
t_symbol *sym___greater____greater__;
t_symbol *sym___greater____tilde__;
t_symbol *sym___hash__A;
t_symbol *sym___hash__N;
t_symbol *sym___hash__X;
t_symbol *sym___less__;
t_symbol *sym___less____equals__;
t_symbol *sym___less____less__;
t_symbol *sym___less____tilde__;
t_symbol *sym___minus__;
t_symbol *sym___minus____tilde__;
t_symbol *sym___percent__;
t_symbol *sym___percent__s;
t_symbol *sym___plus__;
t_symbol *sym___plus____tilde__;
t_symbol *sym___point__aif;
t_symbol *sym___point__aiff;
t_symbol *sym___point__snd;
t_symbol *sym___point__wav;
t_symbol *sym___question__;
t_symbol *sym___semicolon__;
t_symbol *sym___slash__;
t_symbol *sym___slash____tilde__;
t_symbol *sym__autorelease;
t_symbol *sym__autoreleaseA;
t_symbol *sym__autoreleaseB;
t_symbol *sym__bendin;
t_symbol *sym__closebang;
t_symbol *sym__ctlin;
t_symbol *sym__dsp;
t_symbol *sym__dspstatus;
t_symbol *sym__include;
t_symbol *sym__inlet2;
t_symbol *sym__inlet3;
t_symbol *sym__loadbang;
t_symbol *sym__midiports;
t_symbol *sym__midisystemin;
t_symbol *sym__midisystemportin;
t_symbol *sym__notein;
t_symbol *sym__pgmin;
t_symbol *sym__polling;
t_symbol *sym__polytouchin;
t_symbol *sym__restore;
t_symbol *sym__set;
t_symbol *sym__signals;
t_symbol *sym__sysexin;
t_symbol *sym__sysexportin;
t_symbol *sym__tagcanvas;
t_symbol *sym__tagdollarzero;
t_symbol *sym__tagobject;
t_symbol *sym__tagobjectsource;
t_symbol *sym__touchin;
t_symbol *sym_a;
t_symbol *sym_abs;
t_symbol *sym_abs__tilde__;
t_symbol *sym_acoustic;
t_symbol *sym_acoustic__tilde__;
t_symbol *sym_activesense;
t_symbol *sym_adc__tilde__;
t_symbol *sym_add;
t_symbol *sym_addcomma;
t_symbol *sym_adddollar;
t_symbol *sym_adddollarsymbol;
t_symbol *sym_addsemicolon;
t_symbol *sym_aiff;
t_symbol *sym_amptodb;
t_symbol *sym_amptodb__tilde__;
t_symbol *sym_append;
t_symbol *sym_arguments;
t_symbol *sym_arithmetic;
t_symbol *sym_arithmetic__tilde__;
t_symbol *sym_array;
t_symbol *sym_array__space__get;
t_symbol *sym_array__space__max;
t_symbol *sym_array__space__min;
t_symbol *sym_array__space__quantile;
t_symbol *sym_array__space__random;
t_symbol *sym_array__space__set;
t_symbol *sym_array__space__size;
t_symbol *sym_array__space__sum;
t_symbol *sym_atan;
t_symbol *sym_atan2;
t_symbol *sym_audio;
t_symbol *sym_automatic;
t_symbol *sym_b;
t_symbol *sym_back;
t_symbol *sym_bag;
t_symbol *sym_bang__tilde__;
t_symbol *sym_bendin;
t_symbol *sym_bendout;
t_symbol *sym_big;
t_symbol *sym_bindlist;
t_symbol *sym_biquad__tilde__;
t_symbol *sym_bitwise;
t_symbol *sym_block__tilde__;
t_symbol *sym_blocksize;
t_symbol *sym_bng;
t_symbol *sym_bp__tilde__;
t_symbol *sym_bundle;
t_symbol *sym_buttonsnumber;
t_symbol *sym_bytes;
t_symbol *sym_cancel;
t_symbol *sym_canvas;
t_symbol *sym_canvasmaker;
t_symbol *sym_catch__tilde__;
t_symbol *sym_chain;
t_symbol *sym_change;
t_symbol *sym_channels;
t_symbol *sym_class;
t_symbol *sym_clear;
t_symbol *sym_clip;
t_symbol *sym_clip__tilde__;
t_symbol *sym_clock;
t_symbol *sym_close;
t_symbol *sym_closebang;
t_symbol *sym_cnv;
t_symbol *sym_comma;
t_symbol *sym_comment;
t_symbol *sym_connect;
t_symbol *sym_console;
t_symbol *sym_constant;
t_symbol *sym_continue;
t_symbol *sym_coords;
t_symbol *sym_cos;
t_symbol *sym_cos__tilde__;
t_symbol *sym_cosinesum;
t_symbol *sym_count;
t_symbol *sym_counter;
t_symbol *sym_cpole__tilde__;
t_symbol *sym_cputime;
t_symbol *sym_create;
t_symbol *sym_ctlin;
t_symbol *sym_ctlout;
t_symbol *sym_cut;
t_symbol *sym_cv;
t_symbol *sym_czero__tilde__;
t_symbol *sym_czero_rev__tilde__;
t_symbol *sym_dac__tilde__;
t_symbol *sym_data;
t_symbol *sym_dbtoamp;
t_symbol *sym_dbtoamp__tilde__;
t_symbol *sym_dbtopow;
t_symbol *sym_dbtopow__tilde__;
t_symbol *sym_dbtorms;
t_symbol *sym_dbtorms__tilde__;
t_symbol *sym_de__dash__encapsulate;
t_symbol *sym_define;
t_symbol *sym_del;
t_symbol *sym_delay;
t_symbol *sym_delete;
t_symbol *sym_delread4__tilde__;
t_symbol *sym_delread__tilde__;
t_symbol *sym_delwrite__tilde__;
t_symbol *sym_dial;
t_symbol *sym_directories;
t_symbol *sym_discard;
t_symbol *sym_disconnect;
t_symbol *sym_div;
t_symbol *sym_dollar;
t_symbol *sym_dsp;
t_symbol *sym_dspstatus;
t_symbol *sym_duplicate;
t_symbol *sym_elapsed;
t_symbol *sym_embed;
t_symbol *sym_encapsulate;
t_symbol *sym_endianness;
t_symbol *sym_env__tilde__;
t_symbol *sym_envelope;
t_symbol *sym_equal;
t_symbol *sym_exp;
t_symbol *sym_exp__tilde__;
t_symbol *sym_expansion;
t_symbol *sym_expr;
t_symbol *sym_expression;
t_symbol *sym_f;
t_symbol *sym_false;
t_symbol *sym_fft__tilde__;
t_symbol *sym_flashtime;
t_symbol *sym_floatatom;
t_symbol *sym_floatinlet;
t_symbol *sym_flush;
t_symbol *sym_format;
t_symbol *sym_frames;
t_symbol *sym_framp__tilde__;
t_symbol *sym_freeze;
t_symbol *sym_fromlist;
t_symbol *sym_fromsymbol;
t_symbol *sym_front;
t_symbol *sym_fswap;
t_symbol *sym_ftom;
t_symbol *sym_ftom__tilde__;
t_symbol *sym_garray;
t_symbol *sym_gatom;
t_symbol *sym_get;
t_symbol *sym_graph;
t_symbol *sym_group;
t_symbol *sym_help;
t_symbol *sym_hip__tilde__;
t_symbol *sym_hold;
t_symbol *sym_hradio;
t_symbol *sym_hsl;
t_symbol *sym_hslider;
t_symbol *sym_i;
t_symbol *sym_ifft__tilde__;
t_symbol *sym_inlet;
t_symbol *sym_inlet__tilde__;
t_symbol *sym_input;
t_symbol *sym_insert;
t_symbol *sym_int;
t_symbol *sym_iterate;
t_symbol *sym_l;
t_symbol *sym_length;
t_symbol *sym_line;
t_symbol *sym_line__tilde__;
t_symbol *sym_linear;
t_symbol *sym_list__space__append;
t_symbol *sym_list__space__change;
t_symbol *sym_list__space__equal;
t_symbol *sym_list__space__fromsymbol;
t_symbol *sym_list__space__group;
t_symbol *sym_list__space__iterate;
t_symbol *sym_list__space__length;
t_symbol *sym_list__space__prepend;
t_symbol *sym_list__space__reverse;
t_symbol *sym_list__space__rotate;
t_symbol *sym_list__space__scramble;
t_symbol *sym_list__space__sort;
t_symbol *sym_list__space__split;
t_symbol *sym_list__space__store;
t_symbol *sym_list__space__stream;
t_symbol *sym_list__space__sum;
t_symbol *sym_list__space__tosymbol;
t_symbol *sym_list__space__trim;
t_symbol *sym_listen;
t_symbol *sym_listinlet;
t_symbol *sym_little;
t_symbol *sym_loadbang;
t_symbol *sym_loader;
t_symbol *sym_loadmess;
t_symbol *sym_localhost;
t_symbol *sym_log;
t_symbol *sym_log__tilde__;
t_symbol *sym_logarithmic;
t_symbol *sym_logged;
t_symbol *sym_logical;
t_symbol *sym_logical__tilde__;
t_symbol *sym_lop__tilde__;
t_symbol *sym_lrshift__tilde__;
t_symbol *sym_mag__tilde__;
t_symbol *sym_makefilename;
t_symbol *sym_makenote;
t_symbol *sym_math;
t_symbol *sym_math__tilde__;
t_symbol *sym_max;
t_symbol *sym_max__tilde__;
t_symbol *sym_maximum;
t_symbol *sym_menu;
t_symbol *sym_menubutton;
t_symbol *sym_message;
t_symbol *sym_messageresponder;
t_symbol *sym_metadata;
t_symbol *sym_metro;
t_symbol *sym_midiports;
t_symbol *sym_midisystemin;
t_symbol *sym_midisystemout;
t_symbol *sym_millisecond;
t_symbol *sym_min;
t_symbol *sym_min__tilde__;
t_symbol *sym_minimum;
t_symbol *sym_minute;
t_symbol *sym_mixed;
t_symbol *sym_mod;
t_symbol *sym_mode;
t_symbol *sym_moses;
t_symbol *sym_motion;
t_symbol *sym_msg;
t_symbol *sym_mtof;
t_symbol *sym_mtof__tilde__;
t_symbol *sym_multiple;
t_symbol *sym_name;
t_symbol *sym_nbx;
t_symbol *sym_near;
t_symbol *sym_netreceive;
t_symbol *sym_netsend;
t_symbol *sym_next;
t_symbol *sym_noise__tilde__;
t_symbol *sym_nonzero;
t_symbol *sym_normalize;
t_symbol *sym_note;
t_symbol *sym_notein;
t_symbol *sym_noteout;
t_symbol *sym_null;
t_symbol *sym_obj;
t_symbol *sym_object;
t_symbol *sym_objectmaker;
t_symbol *sym_open;
t_symbol *sym_osc__tilde__;
t_symbol *sym_oscbundle;
t_symbol *sym_oscformat;
t_symbol *sym_oscparse;
t_symbol *sym_oscstream;
t_symbol *sym_out;
t_symbol *sym_outlet;
t_symbol *sym_outlet__tilde__;
t_symbol *sym_output;
t_symbol *sym_pack;
t_symbol *sym_pad;
t_symbol *sym_pak;
t_symbol *sym_panel;
t_symbol *sym_paste;
t_symbol *sym_path;
t_symbol *sym_pd;
t_symbol *sym_peaks;
t_symbol *sym_period;
t_symbol *sym_permillisecond;
t_symbol *sym_perminute;
t_symbol *sym_persecond;
t_symbol *sym_pgmin;
t_symbol *sym_pgmout;
t_symbol *sym_phasor__tilde__;
t_symbol *sym_pipe;
t_symbol *sym_pitch;
t_symbol *sym_poly;
t_symbol *sym_polytouchin;
t_symbol *sym_polytouchout;
t_symbol *sym_pop;
t_symbol *sym_pow;
t_symbol *sym_pow__tilde__;
t_symbol *sym_powtodb;
t_symbol *sym_powtodb__tilde__;
t_symbol *sym_prepend;
t_symbol *sym_previous;
t_symbol *sym_print;
t_symbol *sym_print__tilde__;
t_symbol *sym_put;
t_symbol *sym_qlist;
t_symbol *sym_quantile;
t_symbol *sym_quit;
t_symbol *sym_r;
t_symbol *sym_r__tilde__;
t_symbol *sym_radio;
t_symbol *sym_random;
t_symbol *sym_range;
t_symbol *sym_read;
t_symbol *sym_readsf__tilde__;
t_symbol *sym_realtime;
t_symbol *sym_receive;
t_symbol *sym_receive__tilde__;
t_symbol *sym_redo;
t_symbol *sym_remove;
t_symbol *sym_rename;
t_symbol *sym_replace;
t_symbol *sym_resampling;
t_symbol *sym_rescan;
t_symbol *sym_reset;
t_symbol *sym_resize;
t_symbol *sym_restore;
t_symbol *sym_reverse;
t_symbol *sym_rewind;
t_symbol *sym_rfft__tilde__;
t_symbol *sym_rifft__tilde__;
t_symbol *sym_rmag__tilde__;
t_symbol *sym_rmstodb;
t_symbol *sym_rmstodb__tilde__;
t_symbol *sym_rotate;
t_symbol *sym_route;
t_symbol *sym_rpole__tilde__;
t_symbol *sym_rsqrt__tilde__;
t_symbol *sym_rzero__tilde__;
t_symbol *sym_rzero_rev__tilde__;
t_symbol *sym_s;
t_symbol *sym_s__tilde__;
t_symbol *sym_samphold__tilde__;
t_symbol *sym_sample;
t_symbol *sym_samplerate;
t_symbol *sym_samplerate__tilde__;
t_symbol *sym_scalar;
t_symbol *sym_scramble;
t_symbol *sym_search;
t_symbol *sym_second;
t_symbol *sym_seed;
t_symbol *sym_sel;
t_symbol *sym_select;
t_symbol *sym_semicolon;
t_symbol *sym_send;
t_symbol *sym_send__tilde__;
t_symbol *sym_separator;
t_symbol *sym_sequence;
t_symbol *sym_set;
t_symbol *sym_sfthread;
t_symbol *sym_shutdown;
t_symbol *sym_sig__tilde__;
t_symbol *sym_sigmund__tilde__;
t_symbol *sym_signal;
t_symbol *sym_sin;
t_symbol *sym_sinesum;
t_symbol *sym_single;
t_symbol *sym_size;
t_symbol *sym_slider;
t_symbol *sym_snap;
t_symbol *sym_snapshot__tilde__;
t_symbol *sym_songposition;
t_symbol *sym_songselect;
t_symbol *sym_sort;
t_symbol *sym_soundfiler;
t_symbol *sym_soundinfo;
t_symbol *sym_spaghettis;
t_symbol *sym_spigot;
t_symbol *sym_split;
t_symbol *sym_sqrt;
t_symbol *sym_sqrt__tilde__;
t_symbol *sym_stamp;
t_symbol *sym_start;
t_symbol *sym_step;
t_symbol *sym_steps;
t_symbol *sym_stop;
t_symbol *sym_store;
t_symbol *sym_stream;
t_symbol *sym_stripnote;
t_symbol *sym_struct;
t_symbol *sym_substitution;
t_symbol *sym_sum;
t_symbol *sym_support;
t_symbol *sym_swap;
t_symbol *sym_symbolatom;
t_symbol *sym_symbolinlet;
t_symbol *sym_sysexin;
t_symbol *sym_sysexout;
t_symbol *sym_t;
t_symbol *sym_table;
t_symbol *sym_tabosc4__tilde__;
t_symbol *sym_tabplay__tilde__;
t_symbol *sym_tabread;
t_symbol *sym_tabread4;
t_symbol *sym_tabread4__tilde__;
t_symbol *sym_tabread__tilde__;
t_symbol *sym_tabsend__tilde__;
t_symbol *sym_tabreceive__tilde__;
t_symbol *sym_tabwrite;
t_symbol *sym_tabwrite__tilde__;
t_symbol *sym_tan;
t_symbol *sym_tempo;
t_symbol *sym_text;
t_symbol *sym_text__space__define;
t_symbol *sym_text__space__fromlist;
t_symbol *sym_text__space__delete;
t_symbol *sym_text__space__get;
t_symbol *sym_text__space__insert;
t_symbol *sym_text__space__search;
t_symbol *sym_text__space__sequence;
t_symbol *sym_text__space__set;
t_symbol *sym_text__space__size;
t_symbol *sym_text__space__tolist;
t_symbol *sym_textfile;
t_symbol *sym_tgl;
t_symbol *sym_threshold__tilde__;
t_symbol *sym_throw__tilde__;
t_symbol *sym_tick;
t_symbol *sym_timecode;
t_symbol *sym_timer;
t_symbol *sym_timestamp;
t_symbol *sym_tolist;
t_symbol *sym_tosymbol;
t_symbol *sym_touchin;
t_symbol *sym_touchout;
t_symbol *sym_tracks;
t_symbol *sym_trigger;
t_symbol *sym_trim;
t_symbol *sym_true;
t_symbol *sym_tunerequest;
t_symbol *sym_type;
t_symbol *sym_undo;
t_symbol *sym_undoadd;
t_symbol *sym_undoback;
t_symbol *sym_undoconnect;
t_symbol *sym_undocreate;
t_symbol *sym_undocut;
t_symbol *sym_undodeencapsulate;
t_symbol *sym_undodelete;
t_symbol *sym_undodisconnect;
t_symbol *sym_undoduplicate;
t_symbol *sym_undoencapsulate;
t_symbol *sym_undofront;
t_symbol *sym_undomotion;
t_symbol *sym_undopaste;
t_symbol *sym_undoremove;
t_symbol *sym_undoresize;
t_symbol *sym_undoseparator;
t_symbol *sym_undosnap;
t_symbol *sym_unit;
t_symbol *sym_unpack;
t_symbol *sym_until;
t_symbol *sym_urn;
t_symbol *sym_uzi;
t_symbol *sym_v;
t_symbol *sym_value;
t_symbol *sym_vcf__tilde__;
t_symbol *sym_vd__tilde__;
t_symbol *sym_vexpr;
t_symbol *sym_view;
t_symbol *sym_vline__tilde__;
t_symbol *sym_vradio;
t_symbol *sym_vsl;
t_symbol *sym_vslider;
t_symbol *sym_vsnapshot__tilde__;
t_symbol *sym_vu;
t_symbol *sym_wave;
t_symbol *sym_width;
t_symbol *sym_window;
t_symbol *sym_wrap;
t_symbol *sym_wrap__tilde__;
t_symbol *sym_write;
t_symbol *sym_writesf__tilde__;

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

PD_LOCAL void symbols_initialize (void)
{
    sym_JACK                                    = gensym ("JACK");
    sym_Untitled                                = gensym ("Untitled");
    sym__VALUE_                                 = gensym ("_VALUE_");
    sym__SLOT_                                  = gensym ("_SLOT_");
    sym___ampersand__                           = gensym ("&");
    sym___ampersand____ampersand__              = gensym ("&&");
    sym___arrobe__0                             = gensym ("@0");
    sym___arrobe__1                             = gensym ("@1");
    sym___arrobe__2                             = gensym ("@2");
    sym___arrobe__3                             = gensym ("@3");
    sym___arrobe__4                             = gensym ("@4");
    sym___arrobe__5                             = gensym ("@5");
    sym___arrobe__6                             = gensym ("@6");
    sym___arrobe__7                             = gensym ("@7");
    sym___arrobe__8                             = gensym ("@8");
    sym___arrobe__9                             = gensym ("@9");
    sym___arrobe__a                             = gensym ("@a");
    sym___arrobe__b                             = gensym ("@b");
    sym___arrobe__c                             = gensym ("@c");
    sym___arrobe__d                             = gensym ("@d");
    sym___arrobe__e                             = gensym ("@e");
    sym___arrobe__f                             = gensym ("@f");
    sym___asterisk__                            = gensym ("*");
    sym___asterisk____tilde__                   = gensym ("*~");
    sym___bar__                                 = gensym ("|");
    sym___bar____bar__                          = gensym ("||");
    sym___comma__                               = gensym (",");
    sym___dash__                                = gensym ("-");
    sym___dash____asterisk__                    = gensym ("-*");
    sym___dash__aif                             = gensym ("-aif");
    sym___dash__aiff                            = gensym ("-aiff");
    sym___dash__big                             = gensym ("-big");
    sym___dash__binary                          = gensym ("-binary");
    sym___dash__bytes                           = gensym ("-bytes");
    sym___dash__discard                         = gensym ("-discard");
    sym___dash__elapsed                         = gensym ("-elapsed");
    sym___dash__format                          = gensym ("-format");
    sym___dash__frames                          = gensym ("-frames");
    sym___dash__frequency                       = gensym ("-frequency");
    sym___dash__global                          = gensym ("-global");
    sym___dash__growth                          = gensym ("-growth");
    sym___dash__hop                             = gensym ("-hop");
    sym___dash__keep                            = gensym ("-keep");
    sym___dash__little                          = gensym ("-little");
    sym___dash__next                            = gensym ("-next");
    sym___dash__nextstep                        = gensym ("-nextstep");
    sym___dash__none                            = gensym ("-none");
    sym___dash__normalize                       = gensym ("-normalize");
    sym___dash__peaks                           = gensym ("-peaks");
    sym___dash__points                          = gensym ("-points");
    sym___dash__power                           = gensym ("-power");
    sym___dash__resize                          = gensym ("-resize");
    sym___dash__samplerate                      = gensym ("-samplerate");
    sym___dash__skip                            = gensym ("-skip");
    sym___dash__stream                          = gensym ("-stream");
    sym___dash__table                           = gensym ("-table");
    sym___dash__time                            = gensym ("-time");
    sym___dash__udp                             = gensym ("-udp");
    sym___dash__unit                            = gensym ("-unit");
    sym___dash__vibrato                         = gensym ("-vibrato");
    sym___dash__wait                            = gensym ("-wait");
    sym___dash__wave                            = gensym ("-wave");
    sym___equals____equals__                    = gensym ("==");
    sym___exclamation____equals__               = gensym ("!=");
    sym___greater__                             = gensym (">");
    sym___greater____equals__                   = gensym (">=");
    sym___greater____greater__                  = gensym (">>");
    sym___greater____tilde__                    = gensym (">~");
    sym___hash__A                               = gensym ("#A");
    sym___hash__N                               = gensym ("#N");
    sym___hash__X                               = gensym ("#X");
    sym___less__                                = gensym ("<");
    sym___less____equals__                      = gensym ("<=");
    sym___less____less__                        = gensym ("<<");
    sym___less____tilde__                       = gensym ("<~");
    sym___minus__                               = gensym ("-");
    sym___minus____tilde__                      = gensym ("-~");
    sym___percent__                             = gensym ("%");
    sym___percent__s                            = gensym ("%s");
    sym___plus__                                = gensym ("+");
    sym___plus____tilde__                       = gensym ("+~");
    sym___point__aif                            = gensym (".aif");
    sym___point__aiff                           = gensym (".aiff");
    sym___point__snd                            = gensym (".snd");
    sym___point__wav                            = gensym (".wav");
    sym___question__                            = gensym ("?");
    sym___semicolon__                           = gensym (";");
    sym___slash__                               = gensym ("/");
    sym___slash____tilde__                      = gensym ("/~");
    sym__autorelease                            = gensym ("_autorelease");
    sym__autoreleaseA                           = gensym ("_autoreleaseA");
    sym__autoreleaseB                           = gensym ("_autoreleaseB");
    sym__bendin                                 = gensym ("_bendin");
    sym__closebang                              = gensym ("_closebang");
    sym__ctlin                                  = gensym ("_ctlin");
    sym__dsp                                    = gensym ("_dsp");
    sym__dspstatus                              = gensym ("_dspstatus");
    sym__include                                = gensym ("_include");
    sym__inlet2                                 = gensym ("_inlet2");
    sym__inlet3                                 = gensym ("_inlet3");
    sym__loadbang                               = gensym ("_loadbang");
    sym__midiports                              = gensym ("_midiports");
    sym__midisystemin                           = gensym ("_midisystemin");
    sym__midisystemportin                       = gensym ("_midisystemportin");
    sym__notein                                 = gensym ("_notein");
    sym__pgmin                                  = gensym ("_pgmin");
    sym__polling                                = gensym ("_polling");
    sym__polytouchin                            = gensym ("_polytouchin");
    sym__restore                                = gensym ("_restore");
    sym__set                                    = gensym ("_set");
    sym__signals                                = gensym ("_signals");
    sym__sysexin                                = gensym ("_sysexin");
    sym__sysexportin                            = gensym ("_sysexportin");
    sym__tagcanvas                              = gensym ("_tagcanvas");
    sym__tagdollarzero                          = gensym ("_tagdollarzero");
    sym__tagobject                              = gensym ("_tagobject");
    sym__tagobjectsource                        = gensym ("_tagobjectsource");
    sym__touchin                                = gensym ("_touchin");
    sym_a                                       = gensym ("a");
    sym_abs                                     = gensym ("abs");
    sym_abs__tilde__                            = gensym ("abs~");
    sym_acoustic                                = gensym ("acoustic");
    sym_acoustic__tilde__                       = gensym ("acoustic~");
    sym_activesense                             = gensym ("activesense");
    sym_adc__tilde__                            = gensym ("adc~");
    sym_add                                     = gensym ("add");
    sym_addcomma                                = gensym ("addcomma");
    sym_adddollar                               = gensym ("adddollar");
    sym_adddollarsymbol                         = gensym ("adddollarsymbol");
    sym_addsemicolon                            = gensym ("addsemicolon");
    sym_aiff                                    = gensym ("aiff");
    sym_amptodb                                 = gensym ("amptodb");
    sym_amptodb__tilde__                        = gensym ("amptodb~");
    sym_append                                  = gensym ("append");
    sym_arguments                               = gensym ("arguments");
    sym_arithmetic                              = gensym ("arithmetic");
    sym_arithmetic__tilde__                     = gensym ("arithmetic~");
    sym_array                                   = gensym ("array");
    sym_array__space__get                       = gensym ("array get");
    sym_array__space__max                       = gensym ("array max");
    sym_array__space__min                       = gensym ("array min");
    sym_array__space__quantile                  = gensym ("array quantile");
    sym_array__space__random                    = gensym ("array random");
    sym_array__space__set                       = gensym ("array set");
    sym_array__space__size                      = gensym ("array size");
    sym_array__space__sum                       = gensym ("array sum");
    sym_atan                                    = gensym ("atan");
    sym_atan2                                   = gensym ("atan2");
    sym_audio                                   = gensym ("audio");
    sym_automatic                               = gensym ("automatic");
    sym_b                                       = gensym ("b");
    sym_back                                    = gensym ("back");
    sym_bag                                     = gensym ("bag");
    sym_bang__tilde__                           = gensym ("bang~");
    sym_bendin                                  = gensym ("bendin");
    sym_bendout                                 = gensym ("bendout");
    sym_bindlist                                = gensym ("bindlist");
    sym_big                                     = gensym ("big");
    sym_biquad__tilde__                         = gensym ("biquad~");
    sym_bitwise                                 = gensym ("bitwise");
    sym_block__tilde__                          = gensym ("block~");
    sym_blocksize                               = gensym ("blocksize");
    sym_bng                                     = gensym ("bng");
    sym_bp__tilde__                             = gensym ("bp~");
    sym_bundle                                  = gensym ("bundle");
    sym_buttonsnumber                           = gensym ("buttonsnumber");
    sym_bytes                                   = gensym ("bytes");
    sym_cancel                                  = gensym ("cancel");
    sym_canvas                                  = gensym ("canvas");
    sym_canvasmaker                             = gensym ("canvasmaker");
    sym_catch__tilde__                          = gensym ("catch~");
    sym_chain                                   = gensym ("chain");
    sym_change                                  = gensym ("change");
    sym_channels                                = gensym ("channels");
    sym_class                                   = gensym ("class");
    sym_clear                                   = gensym ("clear");
    sym_clip                                    = gensym ("clip");
    sym_clip__tilde__                           = gensym ("clip~");
    sym_clock                                   = gensym ("clock");
    sym_close                                   = gensym ("close");
    sym_closebang                               = gensym ("closebang");
    sym_cnv                                     = gensym ("cnv");
    sym_comma                                   = gensym ("comma");
    sym_comment                                 = gensym ("comment");
    sym_connect                                 = gensym ("connect");
    sym_console                                 = gensym ("console");
    sym_constant                                = gensym ("constant");
    sym_continue                                = gensym ("continue");
    sym_coords                                  = gensym ("coords");
    sym_cos                                     = gensym ("cos");
    sym_cos__tilde__                            = gensym ("cos~");
    sym_cosinesum                               = gensym ("cosinesum");
    sym_count                                   = gensym ("count");
    sym_counter                                 = gensym ("counter");
    sym_cpole__tilde__                          = gensym ("cpole~");
    sym_cputime                                 = gensym ("cputime");
    sym_create                                  = gensym ("create");
    sym_ctlin                                   = gensym ("ctlin");
    sym_ctlout                                  = gensym ("ctlout");
    sym_cut                                     = gensym ("cut");
    sym_cv                                      = gensym ("cv");
    sym_czero__tilde__                          = gensym ("czero~");
    sym_czero_rev__tilde__                      = gensym ("czero_rev~");
    sym_dac__tilde__                            = gensym ("dac~");
    sym_data                                    = gensym ("data");
    sym_dbtoamp                                 = gensym ("dbtoamp");
    sym_dbtoamp__tilde__                        = gensym ("dbtoamp~");
    sym_dbtopow                                 = gensym ("dbtopow");
    sym_dbtopow__tilde__                        = gensym ("dbtopow~");
    sym_dbtorms                                 = gensym ("dbtorms");
    sym_dbtorms__tilde__                        = gensym ("dbtorms~");
    sym_de__dash__encapsulate                   = gensym ("de-encapsulate");
    sym_define                                  = gensym ("define");
    sym_del                                     = gensym ("del");
    sym_delay                                   = gensym ("delay");
    sym_delete                                  = gensym ("delete");
    sym_delread4__tilde__                       = gensym ("delread4~");
    sym_delread__tilde__                        = gensym ("delread~");
    sym_delwrite__tilde__                       = gensym ("delwrite~");
    sym_dial                                    = gensym ("dial");
    sym_directories                             = gensym ("directories");
    sym_discard                                 = gensym ("discard");
    sym_disconnect                              = gensym ("disconnect");
    sym_div                                     = gensym ("div");
    sym_dollar                                  = gensym ("dollar");
    sym_dsp                                     = gensym ("dsp");
    sym_dspstatus                               = gensym ("dspstatus");
    sym_duplicate                               = gensym ("duplicate");
    sym_elapsed                                 = gensym ("elapsed");
    sym_embed                                   = gensym ("embed");
    sym_encapsulate                             = gensym ("encapsulate");
    sym_endianness                              = gensym ("endianness");
    sym_env__tilde__                            = gensym ("env~");
    sym_envelope                                = gensym ("envelope");
    sym_equal                                   = gensym ("equal");
    sym_exp                                     = gensym ("exp");
    sym_exp__tilde__                            = gensym ("exp~");
    sym_expansion                               = gensym ("expansion");
    sym_expr                                    = gensym ("expr");
    sym_expression                              = gensym ("expression");
    sym_f                                       = gensym ("f");
    sym_false                                   = gensym ("false");
    sym_fft__tilde__                            = gensym ("fft~");
    sym_flashtime                               = gensym ("flashtime");
    sym_floatatom                               = gensym ("floatatom");
    sym_floatinlet                              = gensym ("floatinlet");
    sym_flush                                   = gensym ("flush");
    sym_format                                  = gensym ("format");
    sym_frames                                  = gensym ("frames");
    sym_framp__tilde__                          = gensym ("framp~");
    sym_freeze                                  = gensym ("freeze");
    sym_fromlist                                = gensym ("fromlist");
    sym_fromsymbol                              = gensym ("fromsymbol");
    sym_front                                   = gensym ("front");
    sym_fswap                                   = gensym ("fswap");
    sym_ftom                                    = gensym ("ftom");
    sym_ftom__tilde__                           = gensym ("ftom~");
    sym_garray                                  = gensym ("garray");
    sym_gatom                                   = gensym ("gatom");
    sym_get                                     = gensym ("get");
    sym_graph                                   = gensym ("graph");
    sym_group                                   = gensym ("group");
    sym_help                                    = gensym ("help");
    sym_hip__tilde__                            = gensym ("hip~");
    sym_hold                                    = gensym ("hold");
    sym_hradio                                  = gensym ("hradio");
    sym_hsl                                     = gensym ("hsl");
    sym_hslider                                 = gensym ("hslider");
    sym_i                                       = gensym ("i");
    sym_ifft__tilde__                           = gensym ("ifft~");
    sym_inlet                                   = gensym ("inlet");
    sym_inlet__tilde__                          = gensym ("inlet~");
    sym_input                                   = gensym ("input");
    sym_insert                                  = gensym ("insert");
    sym_int                                     = gensym ("int");
    sym_iterate                                 = gensym ("iterate");
    sym_l                                       = gensym ("l");
    sym_length                                  = gensym ("length");
    sym_line                                    = gensym ("line");
    sym_line__tilde__                           = gensym ("line~");
    sym_linear                                  = gensym ("linear");
    sym_list__space__append                     = gensym ("list append");
    sym_list__space__change                     = gensym ("list change");
    sym_list__space__equal                      = gensym ("list equal");
    sym_list__space__fromsymbol                 = gensym ("list fromsymbol");
    sym_list__space__group                      = gensym ("list group");
    sym_list__space__iterate                    = gensym ("list iterate");
    sym_list__space__length                     = gensym ("list length");
    sym_list__space__prepend                    = gensym ("list prepend");
    sym_list__space__reverse                    = gensym ("list reverse");
    sym_list__space__rotate                     = gensym ("list rotate");
    sym_list__space__scramble                   = gensym ("list scramble");
    sym_list__space__sort                       = gensym ("list sort");
    sym_list__space__split                      = gensym ("list split");
    sym_list__space__store                      = gensym ("list store");
    sym_list__space__stream                     = gensym ("list stream");
    sym_list__space__sum                        = gensym ("list sum");
    sym_list__space__tosymbol                   = gensym ("list tosymbol");
    sym_list__space__trim                       = gensym ("list trim");
    sym_listen                                  = gensym ("listen");
    sym_listinlet                               = gensym ("listinlet");
    sym_little                                  = gensym ("little");
    sym_loadbang                                = gensym ("loadbang");
    sym_loader                                  = gensym ("loader");
    sym_loadmess                                = gensym ("loadmess");
    sym_localhost                               = gensym ("localhost");
    sym_log                                     = gensym ("log");
    sym_log__tilde__                            = gensym ("log~");
    sym_logarithmic                             = gensym ("logarithmic");
    sym_logged                                  = gensym ("logged");
    sym_logical                                 = gensym ("logical");
    sym_logical__tilde__                        = gensym ("logical~");
    sym_lop__tilde__                            = gensym ("lop~");
    sym_lrshift__tilde__                        = gensym ("lrshift~");
    sym_mag__tilde__                            = gensym ("mag~");
    sym_makefilename                            = gensym ("makefilename");
    sym_makenote                                = gensym ("makenote");
    sym_math                                    = gensym ("math");
    sym_math__tilde__                           = gensym ("math~");
    sym_max                                     = gensym ("max");
    sym_max__tilde__                            = gensym ("max~");
    sym_maximum                                 = gensym ("maximum");
    sym_menu                                    = gensym ("menu");
    sym_menubutton                              = gensym ("menubutton");
    sym_message                                 = gensym ("message");
    sym_messageresponder                        = gensym ("messageresponder");
    sym_metadata                                = gensym ("metadata");
    sym_metro                                   = gensym ("metro");
    sym_midiports                               = gensym ("midiports");
    sym_midisystemin                            = gensym ("midisystemin");
    sym_midisystemout                           = gensym ("midisystemout");
    sym_millisecond                             = gensym ("millisecond");
    sym_min                                     = gensym ("min");
    sym_min__tilde__                            = gensym ("min~");
    sym_minimum                                 = gensym ("minimum");
    sym_minute                                  = gensym ("minute");
    sym_mixed                                   = gensym ("mixed");
    sym_mod                                     = gensym ("mod");
    sym_mode                                    = gensym ("mode");
    sym_moses                                   = gensym ("moses");
    sym_motion                                  = gensym ("motion");
    sym_msg                                     = gensym ("msg");
    sym_mtof                                    = gensym ("mtof");
    sym_mtof__tilde__                           = gensym ("mtof~");
    sym_multiple                                = gensym ("multiple");
    sym_name                                    = gensym ("name");
    sym_nbx                                     = gensym ("nbx");
    sym_near                                    = gensym ("near");
    sym_netreceive                              = gensym ("netreceive");
    sym_netsend                                 = gensym ("netsend");
    sym_next                                    = gensym ("next");
    sym_noise__tilde__                          = gensym ("noise~");
    sym_nonzero                                 = gensym ("nonzero");
    sym_normalize                               = gensym ("normalize");
    sym_note                                    = gensym ("note");
    sym_notein                                  = gensym ("notein");
    sym_noteout                                 = gensym ("noteout");
    sym_null                                    = gensym ("null");
    sym_obj                                     = gensym ("obj");
    sym_object                                  = gensym ("object");
    sym_objectmaker                             = gensym ("objectmaker");
    sym_open                                    = gensym ("open");
    sym_osc__tilde__                            = gensym ("osc~");
    sym_oscbundle                               = gensym ("oscbundle");
    sym_oscformat                               = gensym ("oscformat");
    sym_oscparse                                = gensym ("oscparse");
    sym_oscstream                               = gensym ("oscstream");
    sym_out                                     = gensym ("out");
    sym_outlet                                  = gensym ("outlet");
    sym_outlet__tilde__                         = gensym ("outlet~");
    sym_output                                  = gensym ("output");
    sym_pack                                    = gensym ("pack");
    sym_pad                                     = gensym ("pad");
    sym_pak                                     = gensym ("pak");
    sym_panel                                   = gensym ("panel");
    sym_paste                                   = gensym ("paste");
    sym_path                                    = gensym ("path");
    sym_pd                                      = gensym ("pd");
    sym_peaks                                   = gensym ("peaks");
    sym_period                                  = gensym ("period");
    sym_permillisecond                          = gensym ("permillisecond");
    sym_perminute                               = gensym ("perminute");
    sym_persecond                               = gensym ("persecond");
    sym_pgmin                                   = gensym ("pgmin");
    sym_pgmout                                  = gensym ("pgmout");
    sym_phasor__tilde__                         = gensym ("phasor~");
    sym_pipe                                    = gensym ("pipe");
    sym_pitch                                   = gensym ("pitch");
    sym_poly                                    = gensym ("poly");
    sym_polytouchin                             = gensym ("polytouchin");
    sym_polytouchout                            = gensym ("polytouchout");
    sym_pop                                     = gensym ("pop");
    sym_pow                                     = gensym ("pow");
    sym_pow__tilde__                            = gensym ("pow~");
    sym_powtodb                                 = gensym ("powtodb");
    sym_powtodb__tilde__                        = gensym ("powtodb~");
    sym_prepend                                 = gensym ("prepend");
    sym_previous                                = gensym ("previous");
    sym_print                                   = gensym ("print");
    sym_print__tilde__                          = gensym ("print~");
    sym_put                                     = gensym ("put");
    sym_qlist                                   = gensym ("qlist");
    sym_quantile                                = gensym ("quantile");
    sym_quit                                    = gensym ("quit");
    sym_r                                       = gensym ("r");
    sym_r__tilde__                              = gensym ("r~");
    sym_radio                                   = gensym ("radio");
    sym_random                                  = gensym ("random");
    sym_range                                   = gensym ("range");
    sym_read                                    = gensym ("read");
    sym_readsf__tilde__                         = gensym ("readsf~");
    sym_realtime                                = gensym ("realtime");
    sym_receive                                 = gensym ("receive");
    sym_receive__tilde__                        = gensym ("receive~");
    sym_redo                                    = gensym ("redo");
    sym_remove                                  = gensym ("remove");
    sym_rename                                  = gensym ("rename");
    sym_replace                                 = gensym ("replace");
    sym_resampling                              = gensym ("resampling");
    sym_rescan                                  = gensym ("rescan");
    sym_reset                                   = gensym ("reset");
    sym_resize                                  = gensym ("resize");
    sym_restore                                 = gensym ("restore");
    sym_reverse                                 = gensym ("reverse");
    sym_rewind                                  = gensym ("rewind");
    sym_rfft__tilde__                           = gensym ("rfft~");
    sym_rifft__tilde__                          = gensym ("rifft~");
    sym_rmag__tilde__                           = gensym ("rmag~");
    sym_rmstodb                                 = gensym ("rmstodb");
    sym_rmstodb__tilde__                        = gensym ("rmstodb~");
    sym_rotate                                  = gensym ("rotate");
    sym_route                                   = gensym ("route");
    sym_rpole__tilde__                          = gensym ("rpole~");
    sym_rzero__tilde__                          = gensym ("rzero~");
    sym_rsqrt__tilde__                          = gensym ("rsqrt~");
    sym_rzero_rev__tilde__                      = gensym ("rzero_rev~");
    sym_s                                       = gensym ("s");
    sym_s__tilde__                              = gensym ("s~");
    sym_samphold__tilde__                       = gensym ("samphold~");
    sym_sample                                  = gensym ("sample");
    sym_samplerate                              = gensym ("samplerate");
    sym_samplerate__tilde__                     = gensym ("samplerate~");
    sym_scalar                                  = gensym ("scalar");
    sym_scramble                                = gensym ("scramble");
    sym_search                                  = gensym ("search");
    sym_second                                  = gensym ("second");
    sym_seed                                    = gensym ("seed");
    sym_sel                                     = gensym ("sel");
    sym_select                                  = gensym ("select");
    sym_semicolon                               = gensym ("semicolon");
    sym_send                                    = gensym ("send");
    sym_send__tilde__                           = gensym ("send~");
    sym_separator                               = gensym ("separator");
    sym_sequence                                = gensym ("sequence");
    sym_set                                     = gensym ("set");
    sym_sfthread                                = gensym ("sfthread");
    sym_shutdown                                = gensym ("shutdown");
    sym_sig__tilde__                            = gensym ("sig~");
    sym_sigmund__tilde__                        = gensym ("sigmund~");
    sym_signal                                  = gensym ("signal");
    sym_sin                                     = gensym ("sin");
    sym_sinesum                                 = gensym ("sinesum");
    sym_single                                  = gensym ("single");
    sym_size                                    = gensym ("size");
    sym_slider                                  = gensym ("slider");
    sym_snap                                    = gensym ("snap");
    sym_snapshot__tilde__                       = gensym ("snapshot~");
    sym_songposition                            = gensym ("songposition");
    sym_songselect                              = gensym ("songselect");
    sym_sort                                    = gensym ("sort");
    sym_soundfiler                              = gensym ("soundfiler");
    sym_soundinfo                               = gensym ("soundinfo");
    sym_spaghettis                              = gensym (PD_NAME_LOWERCASE);
    sym_spigot                                  = gensym ("spigot");
    sym_split                                   = gensym ("split");
    sym_sqrt                                    = gensym ("sqrt");
    sym_sqrt__tilde__                           = gensym ("sqrt~");
    sym_stamp                                   = gensym ("stamp");
    sym_start                                   = gensym ("start");
    sym_step                                    = gensym ("step");
    sym_steps                                   = gensym ("steps");
    sym_stop                                    = gensym ("stop");
    sym_store                                   = gensym ("store");
    sym_stream                                  = gensym ("stream");
    sym_stripnote                               = gensym ("stripnote");
    sym_struct                                  = gensym ("struct");
    sym_substitution                            = gensym ("substitution");
    sym_sum                                     = gensym ("sum");
    sym_support                                 = gensym ("support");
    sym_swap                                    = gensym ("swap");
    sym_symbolatom                              = gensym ("symbolatom");
    sym_symbolinlet                             = gensym ("symbolinlet");
    sym_sysexin                                 = gensym ("sysexin");
    sym_sysexout                                = gensym ("sysexout");
    sym_t                                       = gensym ("t");
    sym_table                                   = gensym ("table");
    sym_tabosc4__tilde__                        = gensym ("tabosc4~");
    sym_tabplay__tilde__                        = gensym ("tabplay~");
    sym_tabread                                 = gensym ("tabread");
    sym_tabread4                                = gensym ("tabread4");
    sym_tabread4__tilde__                       = gensym ("tabread4~");
    sym_tabread__tilde__                        = gensym ("tabread~");
    sym_tabreceive__tilde__                     = gensym ("tabreceive~");
    sym_tabsend__tilde__                        = gensym ("tabsend~");
    sym_tabwrite                                = gensym ("tabwrite");
    sym_tabwrite__tilde__                       = gensym ("tabwrite~");
    sym_tan                                     = gensym ("tan");
    sym_tempo                                   = gensym ("tempo");
    sym_text                                    = gensym ("text");
    sym_text__space__define                     = gensym ("text define");
    sym_text__space__delete                     = gensym ("text delete");
    sym_text__space__fromlist                   = gensym ("text fromlist");
    sym_text__space__get                        = gensym ("text get");
    sym_text__space__insert                     = gensym ("text insert");
    sym_text__space__search                     = gensym ("text search");
    sym_text__space__sequence                   = gensym ("text sequence");
    sym_text__space__set                        = gensym ("text set");
    sym_text__space__size                       = gensym ("text size");
    sym_text__space__tolist                     = gensym ("text tolist");
    sym_textfile                                = gensym ("textfile");
    sym_tgl                                     = gensym ("tgl");
    sym_threshold__tilde__                      = gensym ("threshold~");
    sym_throw__tilde__                          = gensym ("throw~");
    sym_tick                                    = gensym ("tick");
    sym_timecode                                = gensym ("timecode");
    sym_timer                                   = gensym ("timer");
    sym_timestamp                               = gensym ("timestamp");
    sym_tolist                                  = gensym ("tolist");
    sym_tosymbol                                = gensym ("tosymbol");
    sym_touchin                                 = gensym ("touchin");
    sym_touchout                                = gensym ("touchout");
    sym_tracks                                  = gensym ("tracks");
    sym_trigger                                 = gensym ("trigger");
    sym_trim                                    = gensym ("trim");
    sym_true                                    = gensym ("true");
    sym_tunerequest                             = gensym ("tunerequest");
    sym_type                                    = gensym ("type");
    sym_undo                                    = gensym ("undo");
    sym_undoadd                                 = gensym ("undoadd");
    sym_undoback                                = gensym ("undoback");
    sym_undoconnect                             = gensym ("undoconnect");
    sym_undocreate                              = gensym ("undocreate");
    sym_undocut                                 = gensym ("undocut");
    sym_undodelete                              = gensym ("undodelete");
    sym_undodeencapsulate                       = gensym ("undodeencapsulate");
    sym_undodisconnect                          = gensym ("undodisconnect");
    sym_undoduplicate                           = gensym ("undoduplicate");
    sym_undoencapsulate                         = gensym ("undoencapsulate");
    sym_undofront                               = gensym ("undofront");
    sym_undomotion                              = gensym ("undomotion");
    sym_undopaste                               = gensym ("undopaste");
    sym_undoremove                              = gensym ("undoremove");
    sym_undoresize                              = gensym ("undoresize");
    sym_undoseparator                           = gensym ("undoseparator");
    sym_undosnap                                = gensym ("undosnap");
    sym_unit                                    = gensym ("unit");
    sym_unpack                                  = gensym ("unpack");
    sym_until                                   = gensym ("until");
    sym_urn                                     = gensym ("urn");
    sym_uzi                                     = gensym ("uzi");
    sym_v                                       = gensym ("v");
    sym_value                                   = gensym ("value");
    sym_vcf__tilde__                            = gensym ("vcf~");
    sym_vd__tilde__                             = gensym ("vd~");
    sym_vexpr                                   = gensym ("vexpr");
    sym_view                                    = gensym ("view");
    sym_vline__tilde__                          = gensym ("vline~");
    sym_vradio                                  = gensym ("vradio");
    sym_vsl                                     = gensym ("vsl");
    sym_vslider                                 = gensym ("vslider");
    sym_vsnapshot__tilde__                      = gensym ("vsnapshot~");
    sym_vu                                      = gensym ("vu");
    sym_wave                                    = gensym ("wave");
    sym_width                                   = gensym ("width");
    sym_window                                  = gensym ("window");
    sym_wrap                                    = gensym ("wrap");
    sym_wrap__tilde__                           = gensym ("wrap~");
    sym_write                                   = gensym ("write");
    sym_writesf__tilde__                        = gensym ("writesf~");
}

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
