
/* Copyright (c) 1997-2020 Miller Puckette and others. */

/* < https://opensource.org/licenses/BSD-3-Clause > */

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------

#include "../../m_spaghettis.h"
#include "../../m_core.h"

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

PD_LOCAL void clipboard_initialize      (void);
PD_LOCAL void cos_tilde_initialize      (void);
PD_LOCAL void fft_initialize            (void);
PD_LOCAL void fn_initialize             (void);
PD_LOCAL void instance_initialize       (void);
PD_LOCAL void monitor_initialize        (void);
PD_LOCAL void rsqrt_tilde_initialize    (void);

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

PD_LOCAL void clipboard_release         (void);
PD_LOCAL void cos_tilde_release         (void);
PD_LOCAL void fft_release               (void);
PD_LOCAL void fn_release                (void);
PD_LOCAL void instance_release          (void);
PD_LOCAL void loader_release            (void);
PD_LOCAL void monitor_release           (void);
PD_LOCAL void searchpath_release        (void);

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

PD_LOCAL void acoustic_setup            (void);
PD_LOCAL void arguments_setup           (void);
PD_LOCAL void array_setup               (void);
PD_LOCAL void arrayget_setup            (void);
PD_LOCAL void arraymax_setup            (void);
PD_LOCAL void arraymin_setup            (void);
PD_LOCAL void arrayquantile_setup       (void);
PD_LOCAL void arrayrandom_setup         (void);
PD_LOCAL void arrayset_setup            (void);
PD_LOCAL void arraysize_setup           (void);
PD_LOCAL void arraysum_setup            (void);
PD_LOCAL void atan2_setup               (void);
PD_LOCAL void bag_setup                 (void);
PD_LOCAL void bang_setup                (void);
PD_LOCAL void bendin_setup              (void);
PD_LOCAL void bendout_setup             (void);
PD_LOCAL void binop1_setup              (void);
PD_LOCAL void binop2_setup              (void);
PD_LOCAL void binop3_setup              (void);
PD_LOCAL void blocksize_setup           (void);
PD_LOCAL void bng_setup                 (void);
PD_LOCAL void canvas_setup              (void);
PD_LOCAL void chain_setup               (void);
PD_LOCAL void change_setup              (void);
PD_LOCAL void clip_setup                (void);
PD_LOCAL void closebang_setup           (void);
PD_LOCAL void concept_setup             (void);
PD_LOCAL void counter_setup             (void);
PD_LOCAL void ctlin_setup               (void);
PD_LOCAL void ctlout_setup              (void);
PD_LOCAL void delay_setup               (void);
PD_LOCAL void dial_setup                (void);
PD_LOCAL void directories_setup         (void);
PD_LOCAL void dspstatus_setup           (void);
PD_LOCAL void expr_setup                (void);
PD_LOCAL void float_setup               (void);
PD_LOCAL void freeze_setup              (void);
PD_LOCAL void garray_setup              (void);
PD_LOCAL void gatom_setup               (void);
PD_LOCAL void global_setup              (void);
PD_LOCAL void inlet_setup               (void);
PD_LOCAL void int_setup                 (void);
PD_LOCAL void line_setup                (void);
PD_LOCAL void list_setup                (void);
PD_LOCAL void listappend_setup          (void);
PD_LOCAL void listchange_setup          (void);
PD_LOCAL void listequal_setup           (void);
PD_LOCAL void listfromsymbol_setup      (void);
PD_LOCAL void listgroup_setup           (void);
PD_LOCAL void listinlet_setup           (void);
PD_LOCAL void listiterate_setup         (void);
PD_LOCAL void listlength_setup          (void);
PD_LOCAL void listprepend_setup         (void);
PD_LOCAL void listreverse_setup         (void);
PD_LOCAL void listrotate_setup          (void);
PD_LOCAL void listscramble_setup        (void);
PD_LOCAL void listsort_setup            (void);
PD_LOCAL void listsplit_setup           (void);
PD_LOCAL void liststore_setup           (void);
PD_LOCAL void liststream_setup          (void);
PD_LOCAL void listsum_setup             (void);
PD_LOCAL void listtosymbol_setup        (void);
PD_LOCAL void listtrim_setup            (void);
PD_LOCAL void loadbang_setup            (void);
PD_LOCAL void loadmess_setup            (void);
PD_LOCAL void makefilename_setup        (void);
PD_LOCAL void makenote_setup            (void);
PD_LOCAL void math_setup                (void);
PD_LOCAL void menubutton_setup          (void);
PD_LOCAL void message_setup             (void);
PD_LOCAL void metro_setup               (void);
PD_LOCAL void mica_setup                (void);
PD_LOCAL void micaget_setup             (void);
PD_LOCAL void micaindex_setup           (void);
PD_LOCAL void micainfo_setup            (void);
PD_LOCAL void micainterval_setup        (void);
PD_LOCAL void micaitem_setup            (void);
PD_LOCAL void micamap_setup             (void);
PD_LOCAL void micasequence_setup        (void);
PD_LOCAL void micaset_setup             (void);
PD_LOCAL void micaspell_setup           (void);
PD_LOCAL void midiports_setup           (void);
PD_LOCAL void midisystemin_setup        (void);
PD_LOCAL void midisystemout_setup       (void);
PD_LOCAL void moses_setup               (void);
PD_LOCAL void netreceive_setup          (void);
PD_LOCAL void netsend_setup             (void);
PD_LOCAL void notein_setup              (void);
PD_LOCAL void noteout_setup             (void);
PD_LOCAL void oscbundle_setup           (void);
PD_LOCAL void oscformat_setup           (void);
PD_LOCAL void oscparse_setup            (void);
PD_LOCAL void oscstream_setup           (void);
PD_LOCAL void pack_setup                (void);
PD_LOCAL void panel_setup               (void);
PD_LOCAL void pgmin_setup               (void);
PD_LOCAL void pgmout_setup              (void);
PD_LOCAL void pipe_setup                (void);
PD_LOCAL void poly_setup                (void);
PD_LOCAL void polytouchin_setup         (void);
PD_LOCAL void polytouchout_setup        (void);
PD_LOCAL void prepend_setup             (void);
PD_LOCAL void print_setup               (void);
PD_LOCAL void qlist_setup               (void);
PD_LOCAL void radio_setup               (void);
PD_LOCAL void random_setup              (void);
PD_LOCAL void realtime_setup            (void);
PD_LOCAL void receive_setup             (void);
PD_LOCAL void route_setup               (void);
PD_LOCAL void samplerate_setup          (void);
PD_LOCAL void select_setup              (void);
PD_LOCAL void send_setup                (void);
PD_LOCAL void sfthread_setup            (void);
PD_LOCAL void slider_setup              (void);
PD_LOCAL void soundfiler_setup          (void);
PD_LOCAL void soundinfo_setup           (void);
PD_LOCAL void spigot_setup              (void);
PD_LOCAL void stripnote_setup           (void);
PD_LOCAL void swap_setup                (void);
PD_LOCAL void symbol_setup              (void);
PD_LOCAL void tabread_setup             (void);
PD_LOCAL void tabread4_setup            (void);
PD_LOCAL void tabwrite_setup            (void);
PD_LOCAL void text_setup                (void);
PD_LOCAL void textdefine_setup          (void);
PD_LOCAL void textdelete_setup          (void);
PD_LOCAL void textfile_setup            (void);
PD_LOCAL void textget_setup             (void);
PD_LOCAL void textinsert_setup          (void);
PD_LOCAL void textlist_setup            (void);
PD_LOCAL void textsearch_setup          (void);
PD_LOCAL void textsequence_setup        (void);
PD_LOCAL void textset_setup             (void);
PD_LOCAL void textsize_setup            (void);
PD_LOCAL void timer_setup               (void);
PD_LOCAL void timestamp_setup           (void);
PD_LOCAL void toggle_setup              (void);
PD_LOCAL void touchin_setup             (void);
PD_LOCAL void touchout_setup            (void);
PD_LOCAL void trigger_setup             (void);
PD_LOCAL void undoadd_setup             (void);
PD_LOCAL void undoback_setup            (void);
PD_LOCAL void undoconnect_setup         (void);
PD_LOCAL void undocreate_setup          (void);
PD_LOCAL void undocut_setup             (void);
PD_LOCAL void undodeencapsulate_setup   (void);
PD_LOCAL void undodelete_setup          (void);
PD_LOCAL void undodisconnect_setup      (void);
PD_LOCAL void undoduplicate_setup       (void);
PD_LOCAL void undoencapsulate_setup     (void);
PD_LOCAL void undofront_setup           (void);
PD_LOCAL void undomotion_setup          (void);
PD_LOCAL void undopaste_setup           (void);
PD_LOCAL void undoremove_setup          (void);
PD_LOCAL void undoresize_setup          (void);
PD_LOCAL void undoseparator_setup       (void);
PD_LOCAL void undosnap_setup            (void);
PD_LOCAL void unpack_setup              (void);
PD_LOCAL void until_setup               (void);
PD_LOCAL void urn_setup                 (void);
PD_LOCAL void uzi_setup                 (void);
PD_LOCAL void sysexin_setup             (void);
PD_LOCAL void sysexout_setup            (void);
PD_LOCAL void value_setup               (void);
PD_LOCAL void vexpr_setup               (void);
PD_LOCAL void vinlet_setup              (void);
PD_LOCAL void voutlet_setup             (void);
PD_LOCAL void vu_setup                  (void);

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

PD_LOCAL void abs_tilde_setup           (void);
PD_LOCAL void adc_tilde_setup           (void);
PD_LOCAL void add_tilde_setup           (void);
PD_LOCAL void bang_tilde_setup          (void);
PD_LOCAL void biquad_tilde_setup        (void);
PD_LOCAL void block_tilde_setup         (void);
PD_LOCAL void bp_tilde_setup            (void);
PD_LOCAL void catch_tilde_setup         (void);
PD_LOCAL void clip_tilde_setup          (void);
PD_LOCAL void cos_tilde_setup           (void);
PD_LOCAL void cpole_tilde_setup         (void);
PD_LOCAL void czero_rev_tilde_setup     (void);
PD_LOCAL void czero_tilde_setup         (void);
PD_LOCAL void dac_tilde_setup           (void);
PD_LOCAL void dbtopow_tilde_setup       (void);
PD_LOCAL void dbtorms_tilde_setup       (void);
PD_LOCAL void delread_tilde_setup       (void);
PD_LOCAL void delwrite_tilde_setup      (void);
PD_LOCAL void divide_tilde_setup        (void);
PD_LOCAL void env_tilde_setup           (void);
PD_LOCAL void exp_tilde_setup           (void);
PD_LOCAL void fft_tilde_setup           (void);
PD_LOCAL void framp_tilde_setup         (void);
PD_LOCAL void ftom_tilde_setup          (void);
PD_LOCAL void greater_tilde_setup       (void);
PD_LOCAL void hip_tilde_setup           (void);
PD_LOCAL void ifft_tilde_setup          (void);
PD_LOCAL void less_tilde_setup          (void);
PD_LOCAL void line_tilde_setup          (void);
PD_LOCAL void log_tilde_setup           (void);
PD_LOCAL void lop_tilde_setup           (void);
PD_LOCAL void lrshift_tilde_setup       (void);
PD_LOCAL void mag_tilde_setup           (void);
PD_LOCAL void max_tilde_setup           (void);
PD_LOCAL void min_tilde_setup           (void);
PD_LOCAL void mtof_tilde_setup          (void);
PD_LOCAL void multiply_tilde_setup      (void);
PD_LOCAL void noise_tilde_setup         (void);
PD_LOCAL void osc_tilde_setup           (void);
PD_LOCAL void phasor_tilde_setup        (void);
PD_LOCAL void pow_tilde_setup           (void);
PD_LOCAL void powtodb_tilde_setup       (void);
PD_LOCAL void print_tilde_setup         (void);
PD_LOCAL void readsf_tilde_setup        (void);
PD_LOCAL void receive_tilde_setup       (void);
PD_LOCAL void rmag_tilde_setup          (void);
PD_LOCAL void rmstodb_tilde_setup       (void);
PD_LOCAL void rpole_tilde_setup         (void);
PD_LOCAL void rfft_tilde_setup          (void);
PD_LOCAL void rifft_tilde_setup         (void);
PD_LOCAL void rsqrt_tilde_setup         (void);
PD_LOCAL void rzero_rev_tilde_setup     (void);
PD_LOCAL void samphold_tilde_setup      (void);
PD_LOCAL void send_tilde_setup          (void);
PD_LOCAL void sig_tilde_setup           (void);
PD_LOCAL void sigmund_tilde_setup       (void);
PD_LOCAL void snapshot_tilde_setup      (void);
PD_LOCAL void sqrt_tilde_setup          (void);
PD_LOCAL void subtract_tilde_setup      (void);
PD_LOCAL void tabosc4_tilde_setup       (void);
PD_LOCAL void tabplay_tilde_setup       (void);
PD_LOCAL void tabread_tilde_setup       (void);
PD_LOCAL void tabread4_tilde_setup      (void);
PD_LOCAL void tabreceive_tilde_setup    (void);
PD_LOCAL void tabsend_tilde_setup       (void);
PD_LOCAL void tabwrite_tilde_setup      (void);
PD_LOCAL void threshold_tilde_setup     (void);
PD_LOCAL void throw_tilde_setup         (void);
PD_LOCAL void vcf_tilde_setup           (void);
PD_LOCAL void vd_tilde_setup            (void);
PD_LOCAL void wrap_tilde_setup          (void);
PD_LOCAL void writesf_tilde_setup       (void);
PD_LOCAL void zero_tilde_setup          (void);

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

PD_LOCAL void acoustic_destroy          (void);
PD_LOCAL void arguments_destroy         (void);
PD_LOCAL void arrayget_destroy          (void);
PD_LOCAL void arraymax_destroy          (void);
PD_LOCAL void arraymin_destroy          (void);
PD_LOCAL void arrayquantile_destroy     (void);
PD_LOCAL void arrayrandom_destroy       (void);
PD_LOCAL void arrayset_destroy          (void);
PD_LOCAL void arraysize_destroy         (void);
PD_LOCAL void arraysum_destroy          (void);
PD_LOCAL void atan2_destroy             (void);
PD_LOCAL void bag_destroy               (void);
PD_LOCAL void bang_destroy              (void);
PD_LOCAL void bendin_destroy            (void);
PD_LOCAL void bendout_destroy           (void);
PD_LOCAL void binop1_destroy            (void);
PD_LOCAL void binop2_destroy            (void);
PD_LOCAL void binop3_destroy            (void);
PD_LOCAL void blocksize_destroy         (void);
PD_LOCAL void bng_destroy               (void);
PD_LOCAL void canvas_destroy            (void);
PD_LOCAL void chain_destroy             (void);
PD_LOCAL void change_destroy            (void);
PD_LOCAL void clip_destroy              (void);
PD_LOCAL void closebang_destroy         (void);
PD_LOCAL void concept_destroy           (void);
PD_LOCAL void counter_destroy           (void);
PD_LOCAL void ctlin_destroy             (void);
PD_LOCAL void ctlout_destroy            (void);
PD_LOCAL void delay_destroy             (void);
PD_LOCAL void dial_destroy              (void);
PD_LOCAL void directories_destroy       (void);
PD_LOCAL void dspstatus_destroy         (void);
PD_LOCAL void expr_destroy              (void);
PD_LOCAL void float_destroy             (void);
PD_LOCAL void freeze_destroy            (void);
PD_LOCAL void garray_destroy            (void);
PD_LOCAL void gatom_destroy             (void);
PD_LOCAL void global_destroy            (void);
PD_LOCAL void inlet_destroy             (void);
PD_LOCAL void int_destroy               (void);
PD_LOCAL void line_destroy              (void);
PD_LOCAL void listappend_destroy        (void);
PD_LOCAL void listchange_destroy        (void);
PD_LOCAL void listequal_destroy         (void);
PD_LOCAL void listfromsymbol_destroy    (void);
PD_LOCAL void listgroup_destroy         (void);
PD_LOCAL void listinlet_destroy         (void);
PD_LOCAL void listiterate_destroy       (void);
PD_LOCAL void listlength_destroy        (void);
PD_LOCAL void listprepend_destroy       (void);
PD_LOCAL void listreverse_destroy       (void);
PD_LOCAL void listrotate_destroy        (void);
PD_LOCAL void listscramble_destroy      (void);
PD_LOCAL void listsort_destroy          (void);
PD_LOCAL void listsplit_destroy         (void);
PD_LOCAL void liststore_destroy         (void);
PD_LOCAL void liststream_destroy        (void);
PD_LOCAL void listsum_destroy           (void);
PD_LOCAL void listtosymbol_destroy      (void);
PD_LOCAL void listtrim_destroy          (void);
PD_LOCAL void loadbang_destroy          (void);
PD_LOCAL void loadmess_destroy          (void);
PD_LOCAL void makefilename_destroy      (void);
PD_LOCAL void makenote_destroy          (void);
PD_LOCAL void math_destroy              (void);
PD_LOCAL void menubutton_destroy        (void);
PD_LOCAL void message_destroy           (void);
PD_LOCAL void metro_destroy             (void);
PD_LOCAL void micaget_destroy           (void);
PD_LOCAL void micaindex_destroy         (void);
PD_LOCAL void micainfo_destroy          (void);
PD_LOCAL void micainterval_destroy      (void);
PD_LOCAL void micaitem_destroy          (void);
PD_LOCAL void micamap_destroy           (void);
PD_LOCAL void micasequence_destroy      (void);
PD_LOCAL void micaset_destroy           (void);
PD_LOCAL void micaspell_destroy         (void);
PD_LOCAL void midiports_destroy         (void);
PD_LOCAL void midisystemin_destroy      (void);
PD_LOCAL void midisystemout_destroy     (void);
PD_LOCAL void moses_destroy             (void);
PD_LOCAL void netreceive_destroy        (void);
PD_LOCAL void netsend_destroy           (void);
PD_LOCAL void notein_destroy            (void);
PD_LOCAL void noteout_destroy           (void);
PD_LOCAL void oscbundle_destroy         (void);
PD_LOCAL void oscformat_destroy         (void);
PD_LOCAL void oscparse_destroy          (void);
PD_LOCAL void oscstream_destroy         (void);
PD_LOCAL void pack_destroy              (void);
PD_LOCAL void panel_destroy             (void);
PD_LOCAL void pgmin_destroy             (void);
PD_LOCAL void pgmout_destroy            (void);
PD_LOCAL void pipe_destroy              (void);
PD_LOCAL void poly_destroy              (void);
PD_LOCAL void polytouchin_destroy       (void);
PD_LOCAL void polytouchout_destroy      (void);
PD_LOCAL void prepend_destroy           (void);
PD_LOCAL void print_destroy             (void);
PD_LOCAL void qlist_destroy             (void);
PD_LOCAL void radio_destroy             (void);
PD_LOCAL void random_destroy            (void);
PD_LOCAL void realtime_destroy          (void);
PD_LOCAL void receive_destroy           (void);
PD_LOCAL void route_destroy             (void);
PD_LOCAL void samplerate_destroy        (void);
PD_LOCAL void select_destroy            (void);
PD_LOCAL void send_destroy              (void);
PD_LOCAL void sfthread_destroy          (void);
PD_LOCAL void slider_destroy            (void);
PD_LOCAL void soundfiler_destroy        (void);
PD_LOCAL void soundinfo_destroy         (void);
PD_LOCAL void spigot_destroy            (void);
PD_LOCAL void stripnote_destroy         (void);
PD_LOCAL void swap_destroy              (void);
PD_LOCAL void symbol_destroy            (void);
PD_LOCAL void tabread_destroy           (void);
PD_LOCAL void tabread4_destroy          (void);
PD_LOCAL void tabwrite_destroy          (void);
PD_LOCAL void text_destroy              (void);
PD_LOCAL void textdefine_destroy        (void);
PD_LOCAL void textdelete_destroy        (void);
PD_LOCAL void textfile_destroy          (void);
PD_LOCAL void textget_destroy           (void);
PD_LOCAL void textinsert_destroy        (void);
PD_LOCAL void textlist_destroy          (void);
PD_LOCAL void textsearch_destroy        (void);
PD_LOCAL void textsequence_destroy      (void);
PD_LOCAL void textset_destroy           (void);
PD_LOCAL void textsize_destroy          (void);
PD_LOCAL void timer_destroy             (void);
PD_LOCAL void timestamp_destroy         (void);
PD_LOCAL void toggle_destroy            (void);
PD_LOCAL void touchin_destroy           (void);
PD_LOCAL void touchout_destroy          (void);
PD_LOCAL void trigger_destroy           (void);
PD_LOCAL void undoadd_destroy           (void);
PD_LOCAL void undoback_destroy          (void);
PD_LOCAL void undoconnect_destroy       (void);
PD_LOCAL void undocreate_destroy        (void);
PD_LOCAL void undocut_destroy           (void);
PD_LOCAL void undodeencapsulate_destroy (void);
PD_LOCAL void undodelete_destroy        (void);
PD_LOCAL void undodisconnect_destroy    (void);
PD_LOCAL void undoduplicate_destroy     (void);
PD_LOCAL void undoencapsulate_destroy   (void);
PD_LOCAL void undofront_destroy         (void);
PD_LOCAL void undomotion_destroy        (void);
PD_LOCAL void undopaste_destroy         (void);
PD_LOCAL void undoremove_destroy        (void);
PD_LOCAL void undoresize_destroy        (void);
PD_LOCAL void undoseparator_destroy     (void);
PD_LOCAL void undosnap_destroy          (void);
PD_LOCAL void unpack_destroy            (void);
PD_LOCAL void until_destroy             (void);
PD_LOCAL void urn_destroy               (void);
PD_LOCAL void uzi_destroy               (void);
PD_LOCAL void sysexin_destroy           (void);
PD_LOCAL void sysexout_destroy          (void);
PD_LOCAL void value_destroy             (void);
PD_LOCAL void vexpr_destroy             (void);
PD_LOCAL void vinlet_destroy            (void);
PD_LOCAL void voutlet_destroy           (void);
PD_LOCAL void vu_destroy                (void);

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

PD_LOCAL void abs_tilde_destroy         (void);
PD_LOCAL void adc_tilde_destroy         (void);
PD_LOCAL void add_tilde_destroy         (void);
PD_LOCAL void bang_tilde_destroy        (void);
PD_LOCAL void biquad_tilde_destroy      (void);
PD_LOCAL void block_tilde_destroy       (void);
PD_LOCAL void bp_tilde_destroy          (void);
PD_LOCAL void catch_tilde_destroy       (void);
PD_LOCAL void clip_tilde_destroy        (void);
PD_LOCAL void cos_tilde_destroy         (void);
PD_LOCAL void cpole_tilde_destroy       (void);
PD_LOCAL void czero_rev_tilde_destroy   (void);
PD_LOCAL void czero_tilde_destroy       (void);
PD_LOCAL void dac_tilde_destroy         (void);
PD_LOCAL void dbtopow_tilde_destroy     (void);
PD_LOCAL void dbtorms_tilde_destroy     (void);
PD_LOCAL void delread_tilde_destroy     (void);
PD_LOCAL void delwrite_tilde_destroy    (void);
PD_LOCAL void divide_tilde_destroy      (void);
PD_LOCAL void env_tilde_destroy         (void);
PD_LOCAL void exp_tilde_destroy         (void);
PD_LOCAL void fft_tilde_destroy         (void);
PD_LOCAL void framp_tilde_destroy       (void);
PD_LOCAL void ftom_tilde_destroy        (void);
PD_LOCAL void greater_tilde_destroy     (void);
PD_LOCAL void hip_tilde_destroy         (void);
PD_LOCAL void ifft_tilde_destroy        (void);
PD_LOCAL void less_tilde_destroy        (void);
PD_LOCAL void line_tilde_destroy        (void);
PD_LOCAL void log_tilde_destroy         (void);
PD_LOCAL void lop_tilde_destroy         (void);
PD_LOCAL void lrshift_tilde_destroy     (void);
PD_LOCAL void mag_tilde_destroy         (void);
PD_LOCAL void max_tilde_destroy         (void);
PD_LOCAL void min_tilde_destroy         (void);
PD_LOCAL void mtof_tilde_destroy        (void);
PD_LOCAL void multiply_tilde_destroy    (void);
PD_LOCAL void noise_tilde_destroy       (void);
PD_LOCAL void osc_tilde_destroy         (void);
PD_LOCAL void phasor_tilde_destroy      (void);
PD_LOCAL void pow_tilde_destroy         (void);
PD_LOCAL void powtodb_tilde_destroy     (void);
PD_LOCAL void print_tilde_destroy       (void);
PD_LOCAL void readsf_tilde_destroy      (void);
PD_LOCAL void receive_tilde_destroy     (void);
PD_LOCAL void rmag_tilde_destroy        (void);
PD_LOCAL void rmstodb_tilde_destroy     (void);
PD_LOCAL void rpole_tilde_destroy       (void);
PD_LOCAL void rfft_tilde_destroy        (void);
PD_LOCAL void rifft_tilde_destroy       (void);
PD_LOCAL void rsqrt_tilde_destroy       (void);
PD_LOCAL void rzero_rev_tilde_destroy   (void);
PD_LOCAL void samphold_tilde_destroy    (void);
PD_LOCAL void send_tilde_destroy        (void);
PD_LOCAL void sig_tilde_destroy         (void);
PD_LOCAL void sigmund_tilde_destroy     (void);
PD_LOCAL void snapshot_tilde_destroy    (void);
PD_LOCAL void sqrt_tilde_destroy        (void);
PD_LOCAL void subtract_tilde_destroy    (void);
PD_LOCAL void tabosc4_tilde_destroy     (void);
PD_LOCAL void tabplay_tilde_destroy     (void);
PD_LOCAL void tabread_tilde_destroy     (void);
PD_LOCAL void tabread4_tilde_destroy    (void);
PD_LOCAL void tabreceive_tilde_destroy  (void);
PD_LOCAL void tabsend_tilde_destroy     (void);
PD_LOCAL void tabwrite_tilde_destroy    (void);
PD_LOCAL void threshold_tilde_destroy   (void);
PD_LOCAL void throw_tilde_destroy       (void);
PD_LOCAL void vcf_tilde_destroy         (void);
PD_LOCAL void vd_tilde_destroy          (void);
PD_LOCAL void wrap_tilde_destroy        (void);
PD_LOCAL void writesf_tilde_destroy     (void);
PD_LOCAL void zero_tilde_destroy        (void);

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

static void setup_setup (void)
{
    acoustic_setup();
    arguments_setup();
    array_setup();
    arrayget_setup();
    arraymax_setup();
    arraymin_setup();
    arrayquantile_setup();
    arrayrandom_setup();
    arrayset_setup();
    arraysize_setup();
    arraysum_setup();
    atan2_setup();
    bag_setup();
    bang_setup();
    bendin_setup();
    bendout_setup();
    binop1_setup();
    binop2_setup();
    binop3_setup();
    blocksize_setup();
    bng_setup();
    canvas_setup();
    chain_setup();
    change_setup();
    clip_setup();
    closebang_setup();
    concept_setup();
    counter_setup();
    ctlin_setup();
    ctlout_setup();
    delay_setup();
    dial_setup();
    directories_setup();
    dspstatus_setup();
    expr_setup();
    float_setup();
    freeze_setup();
    garray_setup();
    gatom_setup();
    int_setup();
    line_setup();
    list_setup();
    listappend_setup();
    listchange_setup();
    listequal_setup();
    listfromsymbol_setup();
    listgroup_setup();
    listinlet_setup();
    listiterate_setup();
    listlength_setup();
    listprepend_setup();
    listreverse_setup();
    listrotate_setup();
    listscramble_setup();
    listsort_setup();
    listsplit_setup();
    liststore_setup();
    liststream_setup();
    listsum_setup();
    listtosymbol_setup();
    listtrim_setup();
    loadbang_setup();
    loadmess_setup();
    makefilename_setup();
    makenote_setup();
    math_setup();
    menubutton_setup();
    message_setup();
    metro_setup();
    mica_setup();
    micaget_setup();
    micaindex_setup();
    micainfo_setup();
    micainterval_setup();
    micaitem_setup();
    micamap_setup();
    micasequence_setup();
    micaset_setup();
    micaspell_setup();
    midiports_setup();
    midisystemin_setup();
    midisystemout_setup();
    moses_setup();
    netreceive_setup();
    netsend_setup();
    notein_setup();
    noteout_setup();
    oscbundle_setup();
    oscformat_setup();
    oscparse_setup();
    oscstream_setup();
    pack_setup();
    panel_setup();
    pgmin_setup();
    pgmout_setup();
    pipe_setup();
    poly_setup();
    polytouchin_setup();
    polytouchout_setup();
    prepend_setup();
    print_setup();
    qlist_setup();
    radio_setup();
    random_setup();
    realtime_setup();
    receive_setup();
    route_setup();
    samplerate_setup();
    select_setup();
    send_setup();
    sfthread_setup();
    slider_setup();
    soundfiler_setup();
    soundinfo_setup();
    spigot_setup();
    stripnote_setup();
    swap_setup();
    symbol_setup();
    tabread_setup();
    tabread4_setup();
    tabwrite_setup();
    text_setup();
    textdefine_setup();
    textdelete_setup();
    textfile_setup();
    textget_setup();
    textinsert_setup();
    textlist_setup();
    textsearch_setup();
    textsequence_setup();
    textset_setup();
    textsize_setup();
    timer_setup();
    timestamp_setup();
    toggle_setup();
    touchin_setup();
    touchout_setup();
    trigger_setup();
    undoadd_setup();
    undoback_setup();
    undoconnect_setup();
    undocreate_setup();
    undocut_setup();
    undodeencapsulate_setup();
    undodelete_setup();
    undodisconnect_setup();
    undoduplicate_setup();
    undoencapsulate_setup();
    undofront_setup();
    undomotion_setup();
    undopaste_setup();
    undoremove_setup();
    undoresize_setup();
    undoseparator_setup();
    undosnap_setup();
    unpack_setup();
    until_setup();
    urn_setup();
    uzi_setup();
    sysexin_setup();
    sysexout_setup();
    value_setup();
    vexpr_setup();
    vinlet_setup();
    voutlet_setup();
    vu_setup();
    
    abs_tilde_setup();
    adc_tilde_setup();
    add_tilde_setup();
    bang_tilde_setup();
    biquad_tilde_setup();
    block_tilde_setup();
    bp_tilde_setup();
    catch_tilde_setup();
    clip_tilde_setup();
    cos_tilde_setup();
    cpole_tilde_setup();
    czero_tilde_setup();
    czero_rev_tilde_setup();
    dac_tilde_setup();
    dbtopow_tilde_setup();
    dbtorms_tilde_setup();
    delread_tilde_setup();
    delwrite_tilde_setup();
    divide_tilde_setup();
    env_tilde_setup();
    exp_tilde_setup();
    fft_tilde_setup();
    framp_tilde_setup();
    ftom_tilde_setup();
    greater_tilde_setup();
    hip_tilde_setup();
    ifft_tilde_setup();
    less_tilde_setup();
    line_tilde_setup();
    log_tilde_setup();
    lop_tilde_setup();
    lrshift_tilde_setup();
    mag_tilde_setup();
    max_tilde_setup();
    min_tilde_setup();
    mtof_tilde_setup();
    multiply_tilde_setup();
    noise_tilde_setup();
    osc_tilde_setup();
    phasor_tilde_setup();
    pow_tilde_setup();
    powtodb_tilde_setup();
    print_tilde_setup();
    readsf_tilde_setup();
    receive_tilde_setup();
    rfft_tilde_setup();
    rifft_tilde_setup();
    rmag_tilde_setup();
    rmstodb_tilde_setup();
    rpole_tilde_setup();
    rsqrt_tilde_setup();
    rzero_rev_tilde_setup();
    samphold_tilde_setup();
    send_tilde_setup();
    sig_tilde_setup();
    sigmund_tilde_setup();
    snapshot_tilde_setup();
    sqrt_tilde_setup();
    subtract_tilde_setup();
    tabosc4_tilde_setup();
    tabplay_tilde_setup();
    tabread_tilde_setup();
    tabread4_tilde_setup();
    tabreceive_tilde_setup();
    tabsend_tilde_setup();
    tabwrite_tilde_setup();
    threshold_tilde_setup();
    throw_tilde_setup();
    vcf_tilde_setup();
    vd_tilde_setup();
    wrap_tilde_setup();
    writesf_tilde_setup();
    zero_tilde_setup();
}

static void setup_destroy (void)
{
    acoustic_destroy();
    arguments_destroy();
    arrayget_destroy();
    arraymax_destroy();
    arraymin_destroy();
    arrayquantile_destroy();
    arrayrandom_destroy();
    arrayset_destroy();
    arraysize_destroy();
    arraysum_destroy();
    atan2_destroy();
    bag_destroy();
    bang_destroy();
    bendin_destroy();
    bendout_destroy();
    binop1_destroy();
    binop2_destroy();
    binop3_destroy();
    blocksize_destroy();
    bng_destroy();
    canvas_destroy();
    chain_destroy();
    change_destroy();
    clip_destroy();
    closebang_destroy();
    concept_destroy();
    counter_destroy();
    ctlin_destroy();
    ctlout_destroy();
    delay_destroy();
    dial_destroy();
    directories_destroy();
    dspstatus_destroy();
    expr_destroy();
    float_destroy();
    freeze_destroy();
    garray_destroy();
    gatom_destroy();
    int_destroy();
    line_destroy();
    listappend_destroy();
    listchange_destroy();
    listequal_destroy();
    listfromsymbol_destroy();
    listgroup_destroy();
    listinlet_destroy();
    listiterate_destroy();
    listlength_destroy();
    listprepend_destroy();
    listreverse_destroy();
    listrotate_destroy();
    listscramble_destroy();
    listsort_destroy();
    listsplit_destroy();
    liststore_destroy();
    liststream_destroy();
    listsum_destroy();
    listtosymbol_destroy();
    listtrim_destroy();
    loadbang_destroy();
    loadmess_destroy();
    makefilename_destroy();
    makenote_destroy();
    math_destroy();
    menubutton_destroy();
    message_destroy();
    metro_destroy();
    micaget_destroy();
    micaindex_destroy();
    micainfo_destroy();
    micainterval_destroy();
    micaitem_destroy();
    micamap_destroy();
    micasequence_destroy();
    micaset_destroy();
    micaspell_destroy();
    midiports_destroy();
    midisystemin_destroy();
    midisystemout_destroy();
    moses_destroy();
    netreceive_destroy();
    netsend_destroy();
    notein_destroy();
    noteout_destroy();
    oscbundle_destroy();
    oscformat_destroy();
    oscparse_destroy();
    oscstream_destroy();
    pack_destroy();
    panel_destroy();
    pgmin_destroy();
    pgmout_destroy();
    pipe_destroy();
    poly_destroy();
    polytouchin_destroy();
    polytouchout_destroy();
    prepend_destroy();
    print_destroy();
    qlist_destroy();
    radio_destroy();
    random_destroy();
    realtime_destroy();
    receive_destroy();
    route_destroy();
    samplerate_destroy();
    select_destroy();
    send_destroy();
    sfthread_destroy();
    slider_destroy();
    soundfiler_destroy();
    soundinfo_destroy();
    spigot_destroy();
    stripnote_destroy();
    swap_destroy();
    symbol_destroy();
    tabread_destroy();
    tabread4_destroy();
    tabwrite_destroy();
    text_destroy();
    textdefine_destroy();
    textdelete_destroy();
    textfile_destroy();
    textget_destroy();
    textinsert_destroy();
    textlist_destroy();
    textsearch_destroy();
    textsequence_destroy();
    textset_destroy();
    textsize_destroy();
    timer_destroy();
    timestamp_destroy();
    toggle_destroy();
    touchin_destroy();
    touchout_destroy();
    trigger_destroy();
    undoadd_destroy();
    undoback_destroy();
    undoconnect_destroy();
    undocreate_destroy();
    undocut_destroy();
    undodelete_destroy();
    undodeencapsulate_destroy();
    undodisconnect_destroy();
    undoduplicate_destroy();
    undoencapsulate_destroy();
    undofront_destroy();
    undomotion_destroy();
    undopaste_destroy();
    undoremove_destroy();
    undoresize_destroy();
    undoseparator_destroy();
    undosnap_destroy();
    unpack_destroy();
    until_destroy();
    urn_destroy();
    uzi_destroy();
    sysexin_destroy();
    sysexout_destroy();
    value_destroy();
    vexpr_destroy();
    vinlet_destroy();
    voutlet_destroy();
    vu_destroy();
    
    abs_tilde_destroy();
    adc_tilde_destroy();
    add_tilde_destroy();
    bang_tilde_destroy();
    biquad_tilde_destroy();
    block_tilde_destroy();
    bp_tilde_destroy();
    catch_tilde_destroy();
    clip_tilde_destroy();
    cos_tilde_destroy();
    cpole_tilde_destroy();
    czero_tilde_destroy();
    czero_rev_tilde_destroy();
    dac_tilde_destroy();
    dbtopow_tilde_destroy();
    dbtorms_tilde_destroy();
    delread_tilde_destroy();
    delwrite_tilde_destroy();
    divide_tilde_destroy();
    env_tilde_destroy();
    exp_tilde_destroy();
    fft_tilde_destroy();
    framp_tilde_destroy();
    ftom_tilde_destroy();
    greater_tilde_destroy();
    hip_tilde_destroy();
    ifft_tilde_destroy();
    less_tilde_destroy();
    line_tilde_destroy();
    log_tilde_destroy();
    lop_tilde_destroy();
    lrshift_tilde_destroy();
    mag_tilde_destroy();
    max_tilde_destroy();
    min_tilde_destroy();
    mtof_tilde_destroy();
    multiply_tilde_destroy();
    noise_tilde_destroy();
    osc_tilde_destroy();
    phasor_tilde_destroy();
    pow_tilde_destroy();
    powtodb_tilde_destroy();
    print_tilde_destroy();
    readsf_tilde_destroy();
    receive_tilde_destroy();
    rfft_tilde_destroy();
    rifft_tilde_destroy();
    rmag_tilde_destroy();
    rmstodb_tilde_destroy();
    rpole_tilde_destroy();
    rsqrt_tilde_destroy();
    rzero_rev_tilde_destroy();
    samphold_tilde_destroy();
    send_tilde_destroy();
    sig_tilde_destroy();
    sigmund_tilde_destroy();
    snapshot_tilde_destroy();
    sqrt_tilde_destroy();
    subtract_tilde_destroy();
    tabosc4_tilde_destroy();
    tabplay_tilde_destroy();
    tabread_tilde_destroy();
    tabread4_tilde_destroy();
    tabreceive_tilde_destroy();
    tabsend_tilde_destroy();
    tabwrite_tilde_destroy();
    threshold_tilde_destroy();
    throw_tilde_destroy();
    vcf_tilde_destroy();
    vd_tilde_destroy();
    wrap_tilde_destroy();
    writesf_tilde_destroy();
    zero_tilde_destroy();
}

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
// MARK: -

/* Note that order of calls below may be critical. */

PD_LOCAL void setup_initialize (void)
{
    /* First. */
    
    instance_initialize();
    
    /* Second various initializations (alphabetically sorted there). */
    
    clipboard_initialize();
    cos_tilde_initialize();
    fft_initialize();
    fn_initialize();
    monitor_initialize();
    rsqrt_tilde_initialize();
    
    /* Then setup native classes. */
    
    global_setup();
    inlet_setup();
    setup_setup();
}

PD_LOCAL void setup_release (void)
{
    /* Close all remaining patches. */
    
    instance_rootsFreeAll();
    
    /* Destroy all the third-party externals. */
    
    loader_release();
    
    /* Destroy the native classes. */
    
    setup_destroy(); 
    inlet_destroy();
    global_destroy();
    
    /* Various cleaning (reverse order). */
    
    searchpath_release();
    monitor_release();
    fn_release();
    fft_release();
    cos_tilde_release();
    clipboard_release();
    
    /* At last. */
    
    instance_release();
}

// -----------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------
